//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4Aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public string AccountNumber { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ExprirateDate { get; set; }
        public string Opt { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> CreditLimmit { get; set; }
        public string CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
