//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4Aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class otp
    {
        public int id { get; set; }
        public string otp_num { get; set; }
        public Nullable<System.DateTime> expr_time { get; set; }
        public Nullable<int> acc_id { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
