//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project4Aptech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Roll_id { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
